version: '2'
services:
  xform_runner:
    build: .
    command: '"Rscript $${GITHUB_WORKSPACE}/src/xform.R"'
    environment:
      - GITHUB_WORKSPACE=/github/workspace
    volumes:
      - ../../../:/github/workspace
